### ISSUE TITLE
Update route to match nav as you scroll down the page.

### ISSUE THREAD

**Issue by johntyree** [andrayantelo/andrayantelo.github.io#4]
Clicking "Work" takes you to `#projects` but just scrolling down doesn't update the url. This makes copy-paste sharing harder.

**Comment by andrayantelo** [comment]
Off topic, do you think my navbar should be fixed?

**Comment by andrayantelo** [comment]
On topic: would I need to use the history API for this? I've been reading about it and I'm like. wat.

**Comment by andrayantelo** [comment]
https://stackoverflow.com/questions/37513628/check-if-scrolled-past-div-with-javascript-no-jquery

or like that?

**Comment by johntyree** [comment]
https://codepen.io/anon/pen/LdLgNo looks like it does this or something similar?

**Comment by johntyree** [comment]
https://stackoverflow.com/questions/4086107/fixed-page-header-overlaps-in-page-anchors also has some interesting stuff, such as https://css-tricks.com/hash-tag-links-padding/.
